name: nettle-3
git: https://git.lysator.liu.se/nettle/nettle.git
config-commands:
  - ./.bootstrap
  - ./configure
clang-append:
  - -g
  - -O2
tags:
  - nettle_3.0_release_20140607
  - nettle_3.1_release_20150407
  - nettle_3.2_release_20160128
  - nettle_3.3_release_20161001
  - nettle_3.4_release_20171119
  - nettle_3.5_release_20190626
  - nettle_3.6_release_20200429
  - nettle_3.7_release_20210104
  - nettle_3.8_release_20220602
  - nettle_3.9_release_20230514
functions:
  - nettle_sha512_update
  - nettle_sha512_digest
  - nettle_sha256_update
  - nettle_sha256_digest
  - nettle_sha224_digest
  - nettle_sha384_digest
  - nettle_sha512_256_digest
  - nettle_sha512_224_digest
  - nettle_sha3_224_update
  - nettle_sha3_224_digest
  - nettle_sha3_256_update
  - nettle_sha3_256_digest
  - nettle_sha3_384_update
  - nettle_sha3_384_digest
  - nettle_sha3_512_update
  - nettle_sha3_512_digest
  - nettle_sha3_256_shake
  - nettle_streebog256_digest
  - nettle_streebog512_update
  - nettle_streebog512_digest
  - nettle_sm3_update
  - nettle_sm3_digest
  - nettle_md5_update
  - nettle_md5_digest
  - nettle_md4_update
  - nettle_md4_digest
  - nettle_md2_update
  - nettle_md2_digest
  - nettle_ripemd160_update
  - nettle_ripemd160_digest
  - nettle_sha1_update
  - nettle_sha1_digest
  - nettle_gosthash94_update
  - nettle_gosthash94_digest
  - nettle_gosthash94cp_update
  - nettle_gosthash94cp_digest
  - nettle_aes_encrypt
  - nettle_aes_decrypt
  - nettle_arcfour_crypt
  - nettle_arctwo_encrypt
  - nettle_arctwo_decrypt
  - nettle_blowfish_encrypt
  - nettle_blowfish_decrypt
  - nettle_blowfish_bcrypt_hash
  - nettle_blowfish_bcrypt_verify
  - nettle_cast128_encrypt
  - nettle_cast128_decrypt
  - nettle_chacha_crypt
  - nettle_chacha_crypt32
  - nettle_des_encrypt
  - nettle_des_decrypt
  - nettle_des3_encrypt
  - nettle_des3_decrypt
  - nettle_salsa20_crypt
  - nettle_salsa20r12_crypt
  - nettle_twofish_encrypt
  - nettle_twofish_decrypt
  - nettle_cbc_encrypt
  - nettle_cbc_decrypt
  - nettle_ctr_crypt
  - nettle_cfb_encrypt
  - nettle_cfb_decrypt
  - nettle_cfb8_encrypt
  - nettle_cfb8_decrypt
  - nettle_xts_encrypt_message
  - nettle_xts_decrypt_message
  - nettle_eax_encrypt
  - nettle_eax_decrypt
  - nettle_eax_update
  - nettle_eax_digest
  - nettle_gcm_encrypt
  - nettle_gcm_decrypt
  - nettle_gcm_update
  - nettle_gcm_digest
  - nettle_ccm_encrypt
  - nettle_ccm_decrypt
  - nettle_ccm_update
  - nettle_ccm_digest
  - nettle_ccm_encrypt_message
  - nettle_ccm_decrypt_message
  - nettle_chacha_poly1305_encrypt
  - nettle_chacha_poly1305_decrypt
  - nettle_chacha_poly1305_update
  - nettle_chacha_poly1305_digest
  - nettle_siv_cmac_aes128_encrypt_message
  - nettle_siv_cmac_aes128_decrypt_message
  - nettle_siv_cmac_aes256_encrypt_message
  - nettle_siv_cmac_aes256_decrypt_message
  - nettle_hmac_update
  - nettle_hmac_digest
  - nettle_umac32_update
  - nettle_umac32_digest
  - nettle_umac64_update
  - nettle_umac64_digest
  - nettle_umac96_update
  - nettle_umac96_digest
  - nettle_umac128_update
  - nettle_umac128_digest
  - nettle_cmac_aes128_update
  - nettle_cmac_aes128_digest
  - nettle_cmac_aes256_update
  - nettle_cmac_aes256_digest
  - nettle_cmac_des3_update
  - nettle_cmac_des3_digest
  - nettle_poly1305_aes_update
  - nettle_poly1305_aes_digest
  - nettle_hkdf_extract
  - nettle_hkdf_expand
  - nettle_pbkdf2
  - nettle_rsa_md5_sign
  - nettle_rsa_sha1_sign
  - nettle_rsa_sha256_sign
  - nettle_rsa_sha512_sign
  - nettle_rsa_pkcs1_sign
  - nettle_rsa_md5_verify
  - nettle_rsa_sha1_verify
  - nettle_rsa_sha256_verify
  - nettle_rsa_sha512_verify
  - nettle_rsa_pkcs1_verify
  - nettle_rsa_pss_sha256_sign_digest_tr
  - nettle_rsa_pss_sha384_sign_digest_tr
  - nettle_rsa_pss_sha512_sign_digest_tr
  - nettle_rsa_pss_sha256_verify_digest
  - nettle_rsa_pss_sha384_verify_digest
  - nettle_rsa_pss_sha512_verify_digest
  - nettle_rsa_encrypt
  - nettle_rsa_decrypt
  - nettle_dsa_sign
  - nettle_dsa_verify
  - nettle_ecdsa_sign
  - nettle_ecdsa_verify
  - nettle_ed25519_sha512_sign
  - nettle_ed25519_sha512_verify
  - nettle_ed448_shake256_sign
  - nettle_ed448_shake256_verify
  - nettle_base64_encode_single
  - nettle_base64_encode_update
  - nettle_base64_encode_final
  - nettle_base64_decode_single
  - nettle_base64_decode_update
  - nettle_base64_decode_final
  - nettle_base16_encode_single
  - nettle_base16_encode_update
  - nettle_base16_decode_single
  - nettle_base16_decode_update
  - nettle_base16_decode_final
